version: '3'

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: apibara
      MONGO_INITDB_ROOT_PASSWORD: apibara
    ports:
    - 27017:27017
    volumes:
    - ./_docker/apibara_mongodb:/data/db

  indexer:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command:
    - indexer
    - --mongo-url
    - "mongodb://apibara:apibara@mongo:27017"
    - --stream-url
    - "mainnet.starknet.stream.apibara.com"
    - --rpc-url
    - "${STARKNET_RPC_URL}"
    environment:
      PYTHONUNBUFFERED: "1"
    links:
    - mongo

  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
    - 8000:8000
    command:
    - server
    - --mongo-url
    - "mongodb://apibara:apibara@mongo:27017"
    environment:
      PYTHONUNBUFFERED: "1"
    links:
    - mongo